print("upper".upper())
print("Lower".lower())
print("capitalize".capitalize())
print("title title".title())
print("Hello World".count('World'))
print("Hello World".find("World"))
print("Hello World World".rfind("World"))
print("100".isdigit())
print("QWERTY123qwerty".isalnum())
print("QWERTYqwerty".isalpha())
print("QWERTY qwerty".isalpha())
print("qwerty".islower())
print("QWERTY".isupper())
print("Hello World".istitle())
print("   ".isspace())
print(" - ".isspace())
print("Hello World".startswith("H"))
print("Hello World".endswith("d"))
print("H E L L O".split())
print("HELLO, world".split(','))
print(",".join("Hello World"))
print(" ".join("Hello"))
print("   Hello World".strip())
print("-----Hello World-----".strip('-'))
print("Hello world".replace('o', '0'))
print("Hello world".replace('world', 'replace'))
print("Hello world world world".replace(' world', '', 2))